using System;
using System.Collections.Generic;

namespace JDEContext
{
    public partial class F0911Z1
    {
        public string VNEDUS { get; set; }
        public string VNEDTY { get; set; }
        public Nullable<decimal> VNEDSQ { get; set; }
        public string VNEDTN { get; set; }
        public string VNEDCT { get; set; }
        public decimal VNEDLN { get; set; }
        public string VNEDTS { get; set; }
        public string VNEDFT { get; set; }
        public Nullable<int> VNEDDT { get; set; }
        public string VNEDER { get; set; }
        public Nullable<decimal> VNEDDL { get; set; }
        public string VNEDSP { get; set; }
        public string VNEDTC { get; set; }
        public string VNEDTR { get; set; }
        public string VNEDBT { get; set; }
        public string VNEDGL { get; set; }
        public Nullable<decimal> VNEDAN { get; set; }
        public string VNKCO { get; set; }
        public string VNDCT { get; set; }
        public Nullable<decimal> VNDOC { get; set; }
        public Nullable<int> VNDGJ { get; set; }
        public Nullable<decimal> VNJELN { get; set; }
        public string VNEXTL { get; set; }
        public string VNPOST { get; set; }
        public Nullable<decimal> VNICU { get; set; }
        public string VNICUT { get; set; }
        public Nullable<int> VNDICJ { get; set; }
        public Nullable<int> VNDSYJ { get; set; }
        public Nullable<decimal> VNTICU { get; set; }
        public string VNCO { get; set; }
        public string VNANI { get; set; }
        public string VNAM { get; set; }
        public string VNAID { get; set; }
        public string VNMCU { get; set; }
        public string VNOBJ { get; set; }
        public string VNSUB { get; set; }
        public string VNSBL { get; set; }
        public string VNSBLT { get; set; }
        public string VNLT { get; set; }
        public Nullable<decimal> VNPN { get; set; }
        public Nullable<decimal> VNCTRY { get; set; }
        public Nullable<decimal> VNFY { get; set; }
        public string VNFQ { get; set; }
        public string VNCRCD { get; set; }
        public Nullable<decimal> VNCRR { get; set; }
        public Nullable<decimal> VNHCRR { get; set; }
        public Nullable<int> VNHDGJ { get; set; }
        public Nullable<decimal> VNAA { get; set; }
        public Nullable<decimal> VNU { get; set; }
        public string VNUM { get; set; }
        public string VNGLC { get; set; }
        public string VNRE { get; set; }
        public string VNEXA { get; set; }
        public string VNEXR { get; set; }
        public string VNR1 { get; set; }
        public string VNR2 { get; set; }
        public string VNR3 { get; set; }
        public string VNSFX { get; set; }
        public Nullable<decimal> VNODOC { get; set; }
        public string VNODCT { get; set; }
        public string VNOSFX { get; set; }
        public string VNPKCO { get; set; }
        public string VNOKCO { get; set; }
        public string VNPDCT { get; set; }
        public Nullable<decimal> VNAN8 { get; set; }
        public string VNCN { get; set; }
        public Nullable<int> VNDKJ { get; set; }
        public Nullable<int> VNDKC { get; set; }
        public string VNASID { get; set; }
        public string VNBRE { get; set; }
        public string VNRCND { get; set; }
        public string VNSUMM { get; set; }
        public string VNPRGE { get; set; }
        public string VNTNN { get; set; }
        public string VNALT1 { get; set; }
        public string VNALT2 { get; set; }
        public string VNALT3 { get; set; }
        public string VNALT4 { get; set; }
        public string VNALT5 { get; set; }
        public string VNALT6 { get; set; }
        public string VNALT7 { get; set; }
        public string VNALT8 { get; set; }
        public string VNALT9 { get; set; }
        public string VNALT0 { get; set; }
        public string VNALTT { get; set; }
        public string VNALTU { get; set; }
        public string VNALTV { get; set; }
        public string VNALTW { get; set; }
        public string VNALTX { get; set; }
        public string VNALTZ { get; set; }
        public string VNDLNA { get; set; }
        public string VNCFF1 { get; set; }
        public string VNCFF2 { get; set; }
        public string VNASM { get; set; }
        public string VNBC { get; set; }
        public string VNVINV { get; set; }
        public Nullable<int> VNIVD { get; set; }
        public string VNWR01 { get; set; }
        public string VNPO { get; set; }
        public string VNPSFX { get; set; }
        public string VNDCTO { get; set; }
        public Nullable<decimal> VNLNID { get; set; }
        public Nullable<decimal> VNWY { get; set; }
        public Nullable<decimal> VNWN { get; set; }
        public string VNFNLP { get; set; }
        public Nullable<decimal> VNOPSQ { get; set; }
        public string VNJBCD { get; set; }
        public string VNJBST { get; set; }
        public string VNHMCU { get; set; }
        public Nullable<decimal> VNDOI { get; set; }
        public string VNALID { get; set; }
        public string VNALTY { get; set; }
        public Nullable<int> VNDSVJ { get; set; }
        public string VNTORG { get; set; }
        public Nullable<decimal> VNREG_ { get; set; }
        public Nullable<decimal> VNPYID { get; set; }
        public string VNUSER { get; set; }
        public string VNPID { get; set; }
        public string VNJOBN { get; set; }
        public Nullable<int> VNUPMJ { get; set; }
        public Nullable<decimal> VNUPMT { get; set; }
        public string VNCRRM { get; set; }
        public Nullable<decimal> VNACR { get; set; }
        public Nullable<decimal> VNDGM { get; set; }
        public Nullable<decimal> VNDGD { get; set; }
        public Nullable<decimal> VNDGY { get; set; }
        public Nullable<decimal> VNDG_ { get; set; }
        public Nullable<decimal> VNDICM { get; set; }
        public Nullable<decimal> VNDICD { get; set; }
        public Nullable<decimal> VNDICY { get; set; }
        public Nullable<decimal> VNDIC_ { get; set; }
        public Nullable<decimal> VNDSYM { get; set; }
        public Nullable<decimal> VNDSYD { get; set; }
        public Nullable<decimal> VNDSYY { get; set; }
        public Nullable<decimal> VNDSY_ { get; set; }
        public Nullable<decimal> VNDKM { get; set; }
        public Nullable<decimal> VNDKD { get; set; }
        public Nullable<decimal> VNDKY { get; set; }
        public Nullable<decimal> VNDK_ { get; set; }
        public Nullable<decimal> VNDSVM { get; set; }
        public Nullable<decimal> VNDSVD { get; set; }
        public Nullable<decimal> VNDSVY { get; set; }
        public Nullable<decimal> VNDSV_ { get; set; }
        public Nullable<decimal> VNHDGM { get; set; }
        public Nullable<decimal> VNHDGD { get; set; }
        public Nullable<decimal> VNHDGY { get; set; }
        public Nullable<decimal> VNHDG_ { get; set; }
        public Nullable<decimal> VNDKCM { get; set; }
        public Nullable<decimal> VNDKCD { get; set; }
        public Nullable<decimal> VNDKCY { get; set; }
        public Nullable<decimal> VNDKC_ { get; set; }
        public Nullable<decimal> VNIVDM { get; set; }
        public Nullable<decimal> VNIVDD { get; set; }
        public Nullable<decimal> VNIVDY { get; set; }
        public Nullable<decimal> VNIVD_ { get; set; }
        public string VNABR1 { get; set; }
        public string VNABR2 { get; set; }
        public string VNABR3 { get; set; }
        public string VNABR4 { get; set; }
        public string VNABT1 { get; set; }
        public string VNABT2 { get; set; }
        public string VNABT3 { get; set; }
        public string VNABT4 { get; set; }
        public Nullable<decimal> VNITM { get; set; }
        public string VNPM01 { get; set; }
        public string VNPM02 { get; set; }
        public string VNPM03 { get; set; }
        public string VNPM04 { get; set; }
        public string VNPM05 { get; set; }
        public string VNPM06 { get; set; }
        public string VNPM07 { get; set; }
        public string VNPM08 { get; set; }
        public string VNPM09 { get; set; }
        public string VNPM10 { get; set; }
        public string VNBCRC { get; set; }
        public string VNEXR1 { get; set; }
        public string VNTXA1 { get; set; }
        public Nullable<decimal> VNTXITM { get; set; }
        public string VNACTB { get; set; }
        public Nullable<decimal> VNSTAM { get; set; }
        public Nullable<decimal> VNCTAM { get; set; }
        public Nullable<decimal> VNAG { get; set; }
        public Nullable<decimal> VNAGF { get; set; }
        public string VNTKTX { get; set; }
        public Nullable<decimal> VNDLNID { get; set; }
        public string VNCKNU { get; set; }
        public string VNBUPC { get; set; }
        public string VNAHBU { get; set; }
        public string VNEPGC { get; set; }
        public string VNJPGC { get; set; }
        public Nullable<decimal> VNRC5 { get; set; }
        public Nullable<decimal> VNSFXE { get; set; }
        public string VNOFM { get; set; }
    }
}
